name: Build Hidden iOS Dylib

on:
  push:
    branches: [ "**" ] # هذا التعديل يجعل السيرفر يعمل على أي فرع (سواء master أو main أو update)
  workflow_dispatch:   # هذا الخيار يتيح لك تشغيل البناء يدوياً بضغطة زر

jobs:
  build:
    runs-on: macos-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile Dylib for iOS (ARM64)
      run: |
        # استخدام مترجم آبل الرسمي (clang) لبناء المكتبة لمعمارية الآيفون الموحدة
        xcrun --sdk iphoneos clang -dynamiclib -arch arm64 \
          -framework Foundation -framework CoreLocation \
          interpose.m -o AppNetworkCore.dylib
          
    - name: Upload Finished Dylib
      uses: actions/upload-artifact@v4
      with:
        name: Hidden-Location-Dylib
        path: AppNetworkCore.dylib
