name: Build Hidden iOS Dylib

on:
  push:
    branches: [ "**" ] # يعمل على أي فرع تقوم بالحفظ فيه تلقائياً
  workflow_dispatch:   # يتيح لك التشغيل اليدوي بضغطة زر

jobs:
  build:
    runs-on: macos-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile Dylib for iOS (ARM64)
      run: |
        # أمر الترجمة الرسمي لمعمارية الآيفون الحديثة باستخدام مكتبات النظام الأساسية
        xcrun --sdk iphoneos clang -dynamiclib -arch arm64 \
          -framework Foundation -framework CoreLocation \
          interpose.m -o AppNetworkCore.dylib
          
    - name: Upload Finished Dylib
      uses: actions/upload-artifact@v4
      with:
        name: Hidden-Location-Dylib
        path: AppNetworkCore.dylib
